name: ppob
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  equatable: ^2.0.5
  dio: ^5.7.0
  provider: ^6.1.2
  gap: ^3.0.1
  email_validator: ^3.0.0
  shared_preferences: ^2.3.2
  mime: ^2.0.0
  image_picker: ^1.0.0
  http_parser: ^4.0.2
  cached_network_image: ^3.4.1
  intl: ^0.19.0
  currency_text_input_formatter: ^2.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
